Asssignment_1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asssignment_1.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Home()
        {
            return View();
        }
    }
}

Asssignment_1/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asssignment_1.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products
        public ActionResult Product()
        {
            return View();
        }
    }
}

Asssignment_1/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asssignment_1.Controllers
{
    public class ServicesController : Controller
    {
        // GET: Services
        public ActionResult Service()
        {
            return View();
        }
    }
}

Asssignment_1/Views/Home/Home.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>HOME PAGE</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        body {
            position: relative;
        }

        #section1 {
            padding-top: 50px;
            height: 200px;
            color:  blueviolet;
            background-color:  cornflowerblue;
        }

        #section2 {
            padding-top: 50px;
            height: 200px;
            color: #fff;
            background-color: chocolate;
        }
    </style>
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="50">

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">WELCOME TO HOME !!!</a>
            </div>
            <div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        <li><a href="#section1">SERVICES</a></li>
                        <li><a href="#section2">PRODUCTS</a></li>
                   </ul>
                </div>
            </div>
        </div>
    </nav>
    <div id="section1" class="container-fluid">
        <h1>SERVICES</h1>
        <div>
            @Html.ActionLink("Welcome To Services", "Service", "Services")
        </div>
    </div>
    <div id="section2" class="container-fluid">
        <h1>PRODUCTS</h1>
        <div>
            @Html.ActionLink("Welcome To Products", "Product", "Products")
        </div>
    </div>       
</body>
</html>

Asssignment_1/Views/Products/Product.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <h2>PRODUCTS!!!</h2>
        </div>
        
            <div class="dropdown">

                <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">
                    Products Available
                    <span class="caret"></span>
                </button>

                <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Tv</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Fridge</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Washing Machine</a></li>
                </ul>
        

            </div>
    
    </div>
    <center>
        <div>@Html.ActionLink("Welcome To Services", "Service", "Services")</div>

        <div>
            @Html.ActionLink("Welcome To Home", "Home", "Home")
        </div>
    </center>
</body>
</html>

Asssignment_1/Views/Services/Service.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <h2>SERVICES!!!</h2>
        </div>
        <div class="dropdown">

            <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">
                Services offered
                <span class="caret"></span>
            </button>

            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Tv Servicing</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Fridge Servicing</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Washing Machine Servicing</a></li>
            </ul>
        </div>
    </div>
    <center>
        <div>@Html.ActionLink("Welcome To Products", "Product", "Products")</div>

        <div>
            @Html.ActionLink("Welcome To Home", "Home", "Home")
        </div>
    </center>
</body>
</html>